# Generated by Django 6.0.5 on 2026-05-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_bill_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
    ]
